### ISSUE TITLE
virtual machin

### ISSUE THREAD

**Issue by remiznik** [remiznik/engine#2]
Write VM from craftinginterpreters.com
- [x] Strings
- [x] [Hash Tables ](https://app.gitkraken.com/glo/card/8ff71cd86cab41b289cb6bc778d216b9)
- [x] [Global Varibales](https://app.gitkraken.com/glo/card/199238c3b20549c08664079453952488)
- [x] Local Variables
- [x] Jumping Back and Front
- [x] Call and Functions
- [x] Closure 
- [x] Garbege Collection 
- [x] Classes an Onstances
- [x] Methods and Initilizer
- [x] Supperclasses
- [x] Optimization
