### ISSUE TITLE
DebugHellpers 

### ISSUE THREAD

**Issue by remiznik** [remiznik/engine#36]
- [ ]  Добавить функцию времени 
- [ ]  Логгер - выводит на консоль и в файл, макросом чтоб  можно было отключить в разных конфигурациях 
- [ ]  Конфиг движка с разными режимами сборки - дефайны конфигурации с отключением некоторых опый 
- [ ]  Ассерты
